import { Roboto_Flex } from 'next/font/google';

import type { Metadata } from 'next';

import { Providers as TanstackProviders } from '@/providers/tanstack';

import Header from '@/components/layout/header/Header';
import Footer from '@/components/layout/footer/Footer';
import TopLoader from 'nextjs-toploader';

import './globals.css';

const robotoFlex = Roboto_Flex({
    subsets: ['latin'],
    weight: ['400', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={robotoFlex.className}>
                <TopLoader color="#8b5cf6" height={4} showSpinner={false} />
                <TanstackProviders>
                    <Header />
                    {children}
                    <Footer />
                </TanstackProviders>
            </body>
        </html>
    );
}
