import { Roboto_Flex } from 'next/font/google';

import type { Metadata } from 'next';

import Header from '@/components/layout/header/Header';
import Footer from '@/components/layout/footer/Footer';

import './globals.css';

const robotoFlex = Roboto_Flex({
    subsets: ['latin'],
    weight: ['400', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={robotoFlex.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
